name: Laravel CI
on:
  push:
    branches: [ main, staging ]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install composer dependencies
        run: make setup
      - name: Create temporary sqlite database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Run unit tests via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: make test
